# Generated by Django 3.0.2 on 2020-02-23 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gra_blog', '0005_auto_20200223_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 12, 9, 28, 851696, tzinfo=utc)),
        ),
    ]
