# Generated by Django 3.0.2 on 2020-02-23 10:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('branche', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 2, 23, 10, 47, 10, 623613, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 2, 23, 10, 47, 10, 623644, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Type_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 2, 23, 10, 47, 10, 624138, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 2, 23, 10, 47, 10, 624165, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 2, 23, 10, 47, 10, 624658, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 2, 23, 10, 47, 10, 624686, tzinfo=utc))),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gra_reports.Reporter')),
                ('type_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gra_reports.Type_report')),
            ],
            options={
                'ordering': ('headline',),
            },
        ),
    ]
