# Generated by Django 3.0.2 on 2020-02-23 11:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gra_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 11, 32, 7, 205587, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 11, 32, 7, 205669, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 11, 32, 7, 204367, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 11, 32, 7, 204392, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='type_report',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 11, 32, 7, 205020, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='type_report',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 11, 32, 7, 205051, tzinfo=utc)),
        ),
    ]
