# Generated by Django 3.0.2 on 2020-02-23 11:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gra_reports', '0002_auto_20200223_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 11, 40, 4, 734397, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='type_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gra_reports.Type_report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 11, 40, 4, 734419, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 11, 40, 4, 733427, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 11, 40, 4, 733452, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='type_report',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 11, 40, 4, 733916, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='type_report',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 11, 40, 4, 733941, tzinfo=utc)),
        ),
    ]
