# Generated by Django 3.0.2 on 2020-02-23 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gra_reports', '0003_auto_20200223_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 12, 9, 28, 857019, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 12, 9, 28, 857046, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 12, 9, 28, 855704, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 12, 9, 28, 855740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='type_report',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 12, 9, 28, 856420, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='type_report',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 12, 9, 28, 856451, tzinfo=utc)),
        ),
    ]
