# Generated by Django 3.0.2 on 2020-02-23 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gra_reports', '0004_auto_20200223_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 12, 26, 20, 329775, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 12, 26, 20, 329805, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 12, 26, 20, 328530, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 12, 26, 20, 328562, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='type_report',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 12, 26, 20, 329176, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='type_report',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 12, 26, 20, 329207, tzinfo=utc)),
        ),
    ]
