# Generated by Django 3.0.2 on 2020-02-23 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gra_reports', '0005_auto_20200223_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 12, 26, 23, 582917, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 12, 26, 23, 582942, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 12, 26, 23, 581855, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 12, 26, 23, 581883, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='type_report',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 12, 26, 23, 582400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='type_report',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 12, 26, 23, 582426, tzinfo=utc)),
        ),
    ]
