# Generated by Django 3.0.2 on 2020-02-23 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gra_news', '0008_auto_20200223_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 23, 10, 47, 10, 622227, tzinfo=utc)),
        ),
    ]
