# Generated by Django 3.0.2 on 2020-02-23 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gra_news', '0011_auto_20200223_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 23, 12, 9, 28, 853902, tzinfo=utc)),
        ),
    ]
